# Generated by Django 4.2.2 on 2023-06-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '1️⃣'), (2, '2️⃣'), (3, '3️⃣'), (4, '4️⃣'), (5, '5️⃣'), (6, '6️⃣'), (7, '7️⃣'), (8, '8️⃣'), (9, '9️⃣'), (10, '🔟')], default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
