# Generated by Django 4.2.2 on 2023-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_todo_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_detail',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
