# Generated by Django 4.2.2 on 2023-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_todo_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_detail',
            field=models.TextField(blank=True),
        ),
    ]
